import type { BotProfileId } from '../../../src/app/models/player.ts';

export type BotProfile = {
  id: BotProfileId;
  economyWeight: number;
  militaryWeight: number;
  colonizeWeight: number;
  defenseWeight: number;
  spyWeight: number;
  savingsDiscipline: number;
  peaceAcceptanceBias: number;
  allianceAcceptanceBias: number;
  peaceInitiationBias: number;
  allianceInitiationBias: number;
  warPersistenceBias: number;
  recentConflictPenaltyScale: number;
  borderThreatSensitivity: number;
  diplomacyActionThreshold: number;
  minUtilityThreshold: number;
  minAttackStrengthRatio: number;
  reserveFloorRatio: number;
  staleIntelPenaltyScale: number;
  preferredMaxTravelDistance: number;
  maxActionsPerTurn: number;
  maxBuildingActionsPerTurn: number;
  maxResearchActionsPerTurn: number;
  maxShipyardActionsPerTurn: number;
  maxSpyActionsPerTurn: number;
  maxColonizeActionsPerTurn: number;
  maxAttackActionsPerTurn: number;
  maxTransportActionsPerTurn: number;
  maxMaintenanceActionsPerTurn: number;
  maxRecycleActionsPerTurn: number;
  maxRepairActionsPerTurn: number;
  maxBombardActionsPerTurn: number;
  maxSiegeActionsPerTurn: number;
  maxGuardActionsPerTurn: number;
  maxMoveActionsPerTurn: number;
};

export const BOT_PROFILES: Record<BotProfileId, BotProfile> = {
  BALANCED: {
    id: 'BALANCED',
    economyWeight: 1,
    militaryWeight: 1,
    colonizeWeight: 1,
    defenseWeight: 1,
    spyWeight: 1,
    savingsDiscipline: 1,
    peaceAcceptanceBias: 1.5,
    allianceAcceptanceBias: 0.75,
    peaceInitiationBias: 0.9,
    allianceInitiationBias: 0.35,
    warPersistenceBias: 0.75,
    recentConflictPenaltyScale: 0.8,
    borderThreatSensitivity: 1.1,
    diplomacyActionThreshold: 5,
    minUtilityThreshold: 3,
    minAttackStrengthRatio: 1.6,
    reserveFloorRatio: 0.35,
    staleIntelPenaltyScale: 0.12,
    preferredMaxTravelDistance: 6,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 6,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 3,
    maxSpyActionsPerTurn: 1,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 1,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 1,
    maxSiegeActionsPerTurn: 1,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  },
  AGGRESSOR: {
    id: 'AGGRESSOR',
    economyWeight: 0.9,
    militaryWeight: 1.35,
    colonizeWeight: 1.05,
    defenseWeight: 0.8,
    spyWeight: 1.2,
    savingsDiscipline: 0.8,
    peaceAcceptanceBias: -2.5,
    allianceAcceptanceBias: -3,
    peaceInitiationBias: -2.25,
    allianceInitiationBias: -3.25,
    warPersistenceBias: 2.25,
    recentConflictPenaltyScale: 1.15,
    borderThreatSensitivity: 0.45,
    diplomacyActionThreshold: 5.5,
    minUtilityThreshold: 2.5,
    minAttackStrengthRatio: 1.35,
    reserveFloorRatio: 0.25,
    staleIntelPenaltyScale: 0.1,
    preferredMaxTravelDistance: 8,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 5,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 4,
    maxSpyActionsPerTurn: 2,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 1,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 1,
    maxSiegeActionsPerTurn: 1,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  },
  TURTLE: {
    id: 'TURTLE',
    economyWeight: 0.95,
    militaryWeight: 0.85,
    colonizeWeight: 0.8,
    defenseWeight: 1.35,
    spyWeight: 0.8,
    savingsDiscipline: 1.2,
    peaceAcceptanceBias: 2.25,
    allianceAcceptanceBias: 1.25,
    peaceInitiationBias: 1.65,
    allianceInitiationBias: 0.9,
    warPersistenceBias: 0.45,
    recentConflictPenaltyScale: 0.7,
    borderThreatSensitivity: 1.2,
    diplomacyActionThreshold: 4.5,
    minUtilityThreshold: 3,
    minAttackStrengthRatio: 2,
    reserveFloorRatio: 0.45,
    staleIntelPenaltyScale: 0.15,
    preferredMaxTravelDistance: 5,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 6,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 3,
    maxSpyActionsPerTurn: 1,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 1,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 1,
    maxSiegeActionsPerTurn: 0,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  },
  MINER: {
    id: 'MINER',
    economyWeight: 1.35,
    militaryWeight: 0.7,
    colonizeWeight: 1.2,
    defenseWeight: 0.85,
    spyWeight: 0.75,
    savingsDiscipline: 1.3,
    peaceAcceptanceBias: 2,
    allianceAcceptanceBias: 0.5,
    peaceInitiationBias: 1.8,
    allianceInitiationBias: 0.45,
    warPersistenceBias: 0.35,
    recentConflictPenaltyScale: 0.75,
    borderThreatSensitivity: 1,
    diplomacyActionThreshold: 4.5,
    minUtilityThreshold: 3.5,
    minAttackStrengthRatio: 1.9,
    reserveFloorRatio: 0.4,
    staleIntelPenaltyScale: 0.16,
    preferredMaxTravelDistance: 5,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 7,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 2,
    maxSpyActionsPerTurn: 1,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 2,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 1,
    maxSiegeActionsPerTurn: 0,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  },
  AVOIDER: {
    id: 'AVOIDER',
    economyWeight: 1.05,
    militaryWeight: 0.75,
    colonizeWeight: 0.9,
    defenseWeight: 1.1,
    spyWeight: 0.95,
    savingsDiscipline: 1.25,
    peaceAcceptanceBias: 2.75,
    allianceAcceptanceBias: 1.1,
    peaceInitiationBias: 2.2,
    allianceInitiationBias: 0.95,
    warPersistenceBias: 0.2,
    recentConflictPenaltyScale: 0.65,
    borderThreatSensitivity: 1.35,
    diplomacyActionThreshold: 4.25,
    minUtilityThreshold: 3,
    minAttackStrengthRatio: 2.1,
    reserveFloorRatio: 0.45,
    staleIntelPenaltyScale: 0.18,
    preferredMaxTravelDistance: 5,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 6,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 2,
    maxSpyActionsPerTurn: 1,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 1,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 0,
    maxSiegeActionsPerTurn: 0,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  },
  BUNKERER: {
    id: 'BUNKERER',
    economyWeight: 0.9,
    militaryWeight: 0.95,
    colonizeWeight: 0.8,
    defenseWeight: 1.4,
    spyWeight: 0.9,
    savingsDiscipline: 1.15,
    peaceAcceptanceBias: 1.9,
    allianceAcceptanceBias: 0.25,
    peaceInitiationBias: 1.4,
    allianceInitiationBias: 0.2,
    warPersistenceBias: 0.7,
    recentConflictPenaltyScale: 0.85,
    borderThreatSensitivity: 1.15,
    diplomacyActionThreshold: 4.75,
    minUtilityThreshold: 3,
    minAttackStrengthRatio: 1.8,
    reserveFloorRatio: 0.4,
    staleIntelPenaltyScale: 0.13,
    preferredMaxTravelDistance: 5,
    maxActionsPerTurn: 10,
    maxBuildingActionsPerTurn: 6,
    maxResearchActionsPerTurn: 1,
    maxShipyardActionsPerTurn: 3,
    maxSpyActionsPerTurn: 1,
    maxColonizeActionsPerTurn: 1,
    maxAttackActionsPerTurn: 1,
    maxTransportActionsPerTurn: 1,
    maxMaintenanceActionsPerTurn: 1,
    maxRecycleActionsPerTurn: 1,
    maxRepairActionsPerTurn: 1,
    maxBombardActionsPerTurn: 1,
    maxSiegeActionsPerTurn: 0,
    maxGuardActionsPerTurn: 1,
    maxMoveActionsPerTurn: 1
  }
};
